/*  =========================================================================
    zp_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of the ZeroMQ Pipes Project.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZP_CLASSES_H_INCLUDED
#define ZP_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/zp.h"

//  Extra headers

//  Opaque class structures to allow forward references
#ifndef ZPASYNC_T_DEFINED
typedef struct _zpasync_t zpasync_t;
#define ZPASYNC_T_DEFINED
#endif

//  Internal API

#include "zpasync.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef ZP_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
ZP_PRIVATE void
    zpasync_test (bool verbose);

//  Self test for private classes
ZP_PRIVATE void
    zp_private_selftest (bool verbose, const char *subtest);

#endif // ZP_BUILD_DRAFT_API

#endif
